wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700346494.452989
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 53
      - 55
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.9.18
      5: 0.15.11
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss_step
      5: 1
      6:
      - 1
    - 1: val_loss_epoch
      5: 1
      6:
      - 1
    - 1: Reconstruction examples._type
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.sha256
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.size
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.path
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.format
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.width
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.height
      5: 1
      6:
      - 1
    - 1: Reconstruction examples.caption
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
channels:
  desc: null
  value: 8
